### ISSUE TITLE
macOS 10.15 Beta 8

### ISSUE THREAD

**Issue by zmclearan** [rmc-team/bluesky#1]
SkyLight and HIToolbox install without issue in macOS 10.15 Beta 7. When attempting to install these in 10.15b8 HIToolbox installs without problems and SkyLight fails with the following error:

`'/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLightOriginal' not found for '/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight', tried but didn't find: '/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLightOriginal' '/usr/lib/SkyLightOriginal' `

This put the system in an unresponsive state and will prevent the system from starting back up after a reboot. The fix I have found is to re-run Dosdude1's post install utility.

**Comment by julian-fairfax** [comment]
BlueSky requires an update server side to support newer versions. This will be done soon for macOS 10.15 Catalina beta 8 alongside the release of macOS Patcher 3.0 final.

**Comment by saneplate** [comment]
I'm having the same issue.  Any update on a solution?
