### ISSUE TITLE
Menubar Gray 

### ISSUE THREAD

**Issue by pnaambo** [rmc-team/bluesky#2]
hey I applied the patch everything is good looking now except the menu bar is still greyish. is it possible to fix?
am on Catalina 10.15 Beta (19A582a)

**Comment by julian-fairfax** [comment]
Close all apps and use the latest version. It should be working but can be a bit finicky if you have apps using system resources, because they can't be modified correctly.

**Comment by pnaambo** [comment]
thanks it worked. all is the correct color now and even transparent but the volume and display bightness indicators are gray still but at least transparent.
Thanks for this awesome work
