### ISSUE TITLE
Odd breakage

### ISSUE THREAD

**Issue by snhirsch** [rmc-team/bluesky#3]
I installed both packages over 10.14.6 on an "unsupported" Mac Pro 3,1.  A bunch of odd things occurred:

- Desktop startup very slow at login
- XQuartz completely broken.  Windows appear without borders and cannot be moved or resized. Very slow startup.
- Emacs:  Startup extremely slow, entire desktop frozen until window finally appears.

After backing out both patches, XQuartz was still broken and had to be reinstalled.  I think I'm back where I started now.

**Comment by julian-fairfax** [comment]
I'm sorry that you experienced issues. I'll try my best to assist you.
- The desktop starting issue is most likely completely unrelated
- I don't have any knowledge on XQuartz so I can't help with that unfortunately.
- Ditto, have heard of Emacs but haven't used it myself.

**Comment by snhirsch** [comment]
Hi, Julian.

The starting slowdown might have been caused by Finder trying to re-open XQuartz and Emacs, now that I think about it.

XQuartz provides an X11 (Unix/Linux) style environment.  It's free-as-in-beer if you want to try reproducing the issue.  Ditto for Emacs.  I installed the latter using  Macports.

**Comment by julian-fairfax** [comment]
I'm closing this issue as the patch implementation has changed since it was reported.
