### ISSUE TITLE
Issues with macOS 10.15.1

### ISSUE THREAD

**Issue by zmclearan** [rmc-team/bluesky#4]
I reported a problem with Bluesky not installing with macOS 10.15 about a month ago. This issue was resolved with an update to BlueSky. This issue seems to have returned with macOS 10.15.1.

**Comment by zmclearan** [comment]
Thank you for your reply, that is very strange I did not receive an unsupported error. I am in the progress of reinstalling macOS as it seemed to have broken my instal. What is your timetable for releasing an update to BlueSky?

Thank you for all of your hard work with this patch!

**Comment by julian-fairfax** [comment]
Are you using version 1.2? As for the timeline, if the patches themselves are working I’ll have a server-side update for the script and the version with the included resources will be a new download.

**Comment by zmclearan** [comment]
I used the version I previously used with Catalina: release-213013-091019
I also downloaded a copy off of Github this afternoon: release-135127-080819

**Comment by pnaambo** [comment]
tried to patch manually by cp and chmod chown etc but the files seem not to be compatible.
can u please tell me how u changed the original files changing the colours and opacity etc?

**Comment by Marcos144** [comment]
Hello,I'm simpler user using macOS Catalina 10.15.1 trying to fix the dark gray sidebar after installation of Catalina Patcher.Is BlueSky working on that version? And if so, how do I install it?I'm not use to install from the terminal.Thank you in advance and sorry for the inconvenience.

**Comment by julian-fairfax** [comment]
Don’t use BlueSky 1.2 with 10.15.1, it is not supported. I will release an update that supports it soon. In future, wait for updates and don’t try to force unsupported things to install. If you have installed it somehow, the simplest way to fix your machine, is to reinstall macOS. If you require further assistance after I release a new version that supports 10.15.1, you can contact me via Discord, MacRumours, or create a new GitHub issue.

**Comment by julian-fairfax** [comment]
Here you go. https://github.com/rmc-team/bluesky/releases/tag/1.3

**Comment by zmclearan** [comment]
Thanks! I will give this a go later this evening.

**Comment by Marcos144** [comment]
Thank you very much! But question for me now is how to install this patch? I'm not use to terminal or scripts.Any help will be very much appreciated.

**Comment by zomtec** [comment]
@Marcos144 In the Terminal navigate to the script file (bluesky-release-...sh):
`chmod +x bluesky-release-....sh` —> makes the file executable
`sudo ./bluesky-release-....sh` —> runs the script with administrative rights

follow the instructions. After running the script it will reboot instantly (so don’t worry when the screen suddenly goes black).

**Comment by julian-fairfax** [comment]
> @Marcos144 In the Terminal navigate to the script file (bluesky-release-...sh):
> `chmod +x bluesky-release-....sh` —> makes the file executable
> `sudo ./bluesky-release-....sh` —> runs the script with administrative rights
> 
> follow the instructions. After running the script it will reboot instantly (so don’t worry when the screen suddenly goes black).
> 
> @julian-fairfax thanks a lot. :) it’s wonderful some people solve problems I wouldn’t be capable to do... thank you very much.
Thanks for assisting with that user. If anyone requires further assistance after I release a new version that supports 10.15.1, you can contact me via Discord, MacRumours, or create a new GitHub issue.
